#!/usr/bin/env python3
"""
Generate the Home Assistant package (rest_command + helpers + scripts) for the
Arnold soundboard from a directory of (padded) clips.

The package is self-contained and drops into HA's packages/ dir. It builds:
  - rest_command.arnold_doorbell   -> POSTs a clip to go2rtc's backchannel
  - input_select.arnold_clip       -> full library dropdown
  - input_text.arnold_last_played  -> "now playing" readout
  - script.arnold_play(clip)       -> play one clip
  - script.arnold_play_selected    -> play the dropdown selection
  - script.arnold_random           -> play a random *clean* clip

Usage:
  python3 generate_config.py \
      --clips ./arnold \
      --go2rtc http://192.168.1.10:1984 \
      --stream doorbell_talk \
      --container-dir /media/frigate/arnold \
      --out arnold.yaml

Explicit/NSFW basenames listed in EXCLUDE are kept OUT of the random pool
(they're still reachable via the full dropdown).
"""
import argparse, os, glob

# Curate this to taste — keeps the doorbell family-safe when it fires at a visitor.
EXCLUDE = set("""
bastard bitch bullshit bulllllllshit cocaine cocaine-2 cocaine-3 crap-2 drug drug-2
drunkbitch drunkfuck eatme fuass fuckbitch fuckingcrazy fuckingcrazybitch fu guysass
hatedrunk mfbitch ohshit ohshit-2 pissedoff psychobitch psychobitch-2 sob sob-2 stfu
stfu-2 stopbitch stoppussy stopfa screwyou shutup shutup-3x shutupppp wtf wtf-2
wtfgoinon wtfwrong wtfwrong4x youbastards dontfuckbs whatisfnbs wakeupdrunk sourk sac
""".split())


def q(s): return '"' + s.replace('"', '\\"') + '"'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--clips", required=True, help="dir of clip .mp3 files (basenames become clip ids)")
    ap.add_argument("--go2rtc", required=True, help="go2rtc base URL, e.g. http://192.168.1.10:1984")
    ap.add_argument("--stream", default="doorbell_talk")
    ap.add_argument("--container-dir", default="/media/frigate/arnold",
                    help="clip dir path AS SEEN BY the go2rtc/Frigate container")
    ap.add_argument("--out", default="arnold.yaml")
    a = ap.parse_args()

    names = sorted(os.path.basename(p)[:-4] for p in glob.glob(os.path.join(a.clips, "*.mp3")))
    if not names:
        raise SystemExit(f"no .mp3 found in {a.clips}")
    clean = [n for n in names if n not in EXCLUDE]

    url = (f"{a.go2rtc}/api/ffmpeg?dst={a.stream}"
           f"&file={a.container_dir}/{{{{ clip }}}}.mp3")

    L = []
    L += ["# Arnold Soundboard backend (generated by generate_config.py).", ""]
    L += ["rest_command:", "  arnold_doorbell:", "    method: POST",
          f'    url: "{url}"', "    timeout: 20", ""]
    L += ["input_text:", "  arnold_last_played:", "    name: Arnold Last Played",
          "    icon: mdi:bullhorn", "    max: 255", ""]
    L += ["input_select:", "  arnold_clip:", "    name: Arnold Full Library",
          "    icon: mdi:playlist-music", "    options:"]
    L += [f"      - {q(n)}" for n in names]
    L += ["", "script:",
          "  arnold_play:", "    alias: Arnold Play Clip", "    icon: mdi:bullhorn",
          "    mode: restart", "    fields:", "      clip:",
          "        description: Clip basename (no extension)", "        example: choppa",
          "    sequence:", "    - service: rest_command.arnold_doorbell", "      data:",
          '        clip: "{{ clip }}"',
          "    - service: input_text.set_value", "      target:",
          "        entity_id: input_text.arnold_last_played", "      data:",
          '        value: "{{ clip }}"',
          "  arnold_play_selected:", "    alias: Arnold Play Selected",
          "    icon: mdi:play-circle", "    mode: restart", "    sequence:",
          "    - service: script.arnold_play", "      data:",
          "        clip: \"{{ states('input_select.arnold_clip') }}\"",
          "  arnold_random:", "    alias: Arnold Random", "    icon: mdi:shuffle-variant",
          "    mode: restart", "    sequence:", "    - variables:", "        clips:"]
    L += [f"          - {q(n)}" for n in clean]
    L += ["    - service: script.arnold_play", "      data:",
          '        clip: "{{ clips | random }}"']

    open(a.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {a.out}: {len(names)} clips ({len(clean)} in random pool)")


if __name__ == "__main__":
    main()
